name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildLoader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build, tag and push
      run: |
        echo $PAT | docker login ghcr.io -u $USERNAME --password-stdin
        docker build DataLoader -t ghcr.io/worthington10tw/${IMAGE_NAME}:latest
        docker push ghcr.io/worthington10tw/${IMAGE_NAME}:latest
      env:
        IMAGE_NAME: elasticsearchbrownbag-data-loader
        PAT: ${{ secrets.PAT }}
        USERNAME: ${{ secrets.USERNAME }}
  buildConfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build, tag and push
      run: |
        echo $PAT | docker login ghcr.io -u $USERNAME --password-stdin
        docker build ElasticConfig -t ghcr.io/worthington10tw/${IMAGE_NAME}:latest
        docker push ghcr.io/worthington10tw/${IMAGE_NAME}:latest
      env:
        IMAGE_NAME: elasticsearchbrownbag-elastic-config
        PAT: ${{ secrets.PAT }}
        USERNAME: ${{ secrets.USERNAME }}
